@echo off
echo Starting Tailor Shop Application...

echo Starting Backend Server...
start "Backend" cmd /k "cd backend && node index.js"

echo Waiting for backend to initialize...
timeout /t 5 /nobreak >nul

echo Starting Frontend...
npm start

pause
