import React, { createContext, useState, useContext } from 'react';

// Translation strings
const translations = {
  en: {
    // Navigation
    home: 'Home',
    customers: 'Customers--------',
    orders: 'Orders----------',
    
    // Home Screen
    welcome: 'Welcome',
    businessOverview: 'Business Overview',
    quickActions: 'Quick Actions',
    totalCustomers: 'Total Customers',
    totalOrders: 'Total Orders',
    pendingOrders: 'Pending Orders',
    completedOrders: 'Completed Orders',
    tailorShop: 'Tailor Shop',
    recentOrders: 'Recent Orders',
    noOrders: 'No orders found',
    addCustomer: 'Add Customer',
    addOrder: 'Add Order',
    viewAll: 'View All',
    quickActions: 'Quick Actions',
    
    // Customer Screen
    customersList: 'Customers List',
    searchNameContact: 'Search name or contact...',
    addNewCustomer: 'Add New Customer',
    customerName: 'Customer Name',
    contactNumber: 'Contact Number',
    address: 'Address',
    saveCustomer: 'Save Customer',
    updateCustomer: 'Update Customer',
    customerNumber: 'Customer Number',
    viewOrders: 'View Orders',
    edit: 'Edit',
    delete: 'Delete',
    noCustomersFound: 'No customers found',
    noOrdersFound: 'No orders found',
    totalOrders: 'Total Orders',
    
    // Order Screen
    ordersList: 'Orders List',
    orderNumber: 'Order Number',
    customer: 'Customer',
    orderDate: 'Order Date',
    deliveryDate: 'Delivery Date',
    status: 'Status',
    amount: 'Amount',
    pending: 'Pending',
    in_progress: 'In Progress',
    ready: 'Ready',
    delivered: 'Delivered',
    cancelled: 'Cancelled',
    createOrder: 'Create Order',
    updateOrder: 'Update Order',
    orderDetails: 'Order Details',
    paymentInformation: 'Payment Information',
    updateStatus: 'Update Status',
    deleteOrder: 'Delete Order',
    viewOrders: 'View Orders',
    
    // Add/Edit Order
    createNewOrder: 'Create New Order',
    editOrder: 'Edit Order',
    customerRequired: 'Customer *',
    garmentTypes: 'Garment Types',
    measurements: 'Measurements',
    designImage: 'Design Image',
    totalAmount: 'Total Amount *',
    advanceAmount: 'Advance Amount',
    notes: 'Notes',
    balanceAmount: 'Balance Amount',
    
    // Measurements
    measurementType: 'Measurement Type',
    value: 'Value',
    unit: 'Unit',
    saveMeasurements: 'Save Measurements',
    
    // Garment Types
    selectGarmentTypes: 'Select Garment Types *',
    kurtiKameezTop: 'Kurti / Kameez / Top',
    salwarPantChuridar: 'Salwar / Pant / Churidar',
    blouseSareeBlouse: 'Blouse (Saree Blouse)',
    lehengaSkirt: 'Lehenga / Skirt',
    gownAnarkali: 'Gown / Anarkali',
    dressWesternWear: 'Dress / Western Wear',
    other: 'Other',
    pleaseSelectAtLeastOneGarmentType: 'Please select at least one garment type',
    
    // Add Order Screen
    noCustomerSelected: 'No customer selected',
    selectCustomer: 'Select Customer',
    customerId: 'Customer ID',
    hide: 'Hide',
    show: 'Show',
    remove: 'Remove',
    tapToUploadDesign: '📷 Tap to upload design',
    updatingOrder: 'Updating Order...',
    creatingOrder: 'Creating Order...',
    addDesignImage: 'Add Design Image',
    totalAmountRequired: 'Please enter total amount',
    garmentTypesRequired: 'Please select at least one garment type',
    orderCreatedSuccessfully: 'Order created successfully',
    orderUpdatedSuccessfully: 'Order updated successfully',
    failedToSaveOrder: 'Failed to save order. Please check all fields and try again.',
    failedToCreateOrder: 'Failed to create order. Please try again.',
    failedToUpdateOrder: 'Failed to update order. Please try again.',
    failedToLoadDesignImage: 'Failed to load design image. Please try again.',
    
    // Alert Messages
    failedToLoadOrders: 'Unable to load orders. Please check your connection and try again.',
    failedToSearchOrders: 'Search completed with no results. Please try different search terms.',
    deleteOrder: 'Delete Order',
    deleteOrderConfirmation: 'Are you sure you want to delete order #{orderNumber}? This action cannot be undone.',
    orderDeletedSuccessfully: 'Order deleted successfully',
    failedToDeleteOrder: 'Unable to delete order. Please try again.',
    orderStatusUpdatedSuccessfully: 'Order status updated successfully',
    failedToUpdateOrderStatus: 'Unable to update order status. Please try again.',
    
    // Error Messages
    error: 'Error',
    loginFailed: 'Login Failed',
    anErrorOccurredDuringLogin: 'Unable to sign in. Please check your credentials and try again.',
    pleaseEnterBothUsernameAndPassword: 'Both username and password are required to continue.',
    customerNameRequired: 'Customer name is required. Please enter a valid name.',
    customerUpdatedSuccessfully: 'Customer information updated successfully',
    customerAddedSuccessfully: 'New customer added successfully',
    failedToSaveCustomer: 'Unable to save customer information. Please check all fields and try again.',
    failedToLoadCustomers: 'Unable to load customer list. Please refresh and try again.',
    failedToSearchCustomers: 'No customers found matching your search criteria.',
    deleteCustomer: 'Delete Customer',
    deleteCustomerConfirmation: 'Are you sure you want to delete {customerName}? All associated orders will remain but customer details will be permanently removed.',
    customerDeletedSuccessfully: 'Customer deleted successfully',
    failedToDeleteCustomer: 'Unable to delete customer. Please try again.',
    measurementsSavedSuccessfully: 'Measurements saved successfully',
    failedToSaveMeasurements: 'Unable to save measurements. Please verify all values and try again.',
    connectionError: 'Connection Error',
    cannotConnectToBackendServer: 'Unable to connect to the server. Please ensure your internet connection is active and the backend server is running.',
    retry: 'Retry',
    ok: 'OK',
    cancel: 'Cancel',
    select: 'Select',
    saving: 'Saving...',
    failedToLoadOrderDetails: 'Unable to load order details. Please refresh and try again.',
    confirmDeleteOrder: 'Are you sure you want to delete this order? This action cannot be undone.',
    
    // Placeholders
    enterYourUsername: 'Enter your username',
    enterYourPassword: 'Enter your password',
    enterCustomerName: 'Enter customer name',
    enterContactNumber: 'Enter contact number',
    enterCustomerAddress: 'Enter customer address',
    searchNameOrContact: 'Search name or contact...',
    
    // Image Picker
    selectImageSource: 'Select Image Source',
    chooseImageSource: 'Choose how you want to add an image',
    camera: 'Camera',
    gallery: 'Gallery',
    permissionRequired: 'Permission Required',
    cameraPermission: 'Camera permission is required to take photos. Please enable camera access in your device settings.',
    cameraRollPermission: 'Photo library permission is required to select images. Please enable photo access in your device settings.',
    failedToPickImage: 'Unable to pick image. Please try again.',
    designImage: 'Design Image',
    tapToUploadDesign: '📷 Tap to upload design image',
    viewFullScreen: 'View Full Screen',
    customer: 'Customer',
    customerNumber: 'Customer #:',
    phone: 'Phone',
    address: 'Address',
    nA: 'N/A',
    order: 'Order',
    orders: 'Orders',
    loadingOrders: 'Loading orders...',
    failedToLoadOrdersError: 'Failed to load orders',
    
    // DatePicker
    january: 'January',
    february: 'February',
    march: 'March',
    april: 'April',
    may: 'May',
    june: 'June',
    july: 'July',
    august: 'August',
    september: 'September',
    october: 'October',
    november: 'November',
    december: 'December',
    
    // API Error Messages
    loginFailedError: 'Login failed',
    failedToFetchCustomers: 'Failed to fetch customers',
    failedToFetchCustomerDetails: 'Failed to fetch customer details',
    failedToAddCustomer: 'Failed to add customer',
    failedToUpdateCustomer: 'Failed to update customer',
    failedToDeleteCustomer: 'Failed to delete customer',
    failedToFetchOrders: 'Failed to fetch orders',
    failedToFetchOrderDetails: 'Failed to fetch order details',
    failedToAddOrder: 'Failed to add order',
    failedToUpdateOrder: 'Failed to update order',
    failedToDeleteOrder: 'Failed to delete order',
    
    // Order Detail Screen
    failedToLoadOrderDetails: 'Failed to load order details',
    confirmDeleteOrder: 'Are you sure you want to delete this order?',
    failedToDeleteOrder: 'Failed to delete order',
    
    // Measurement Screen
    general: 'GENERAL',
    customNotesPlaceholder: 'Add any custom measurement notes or special requirements...',
    additionalMeasurements: 'Additional Measurements',
    customNotes: 'Custom Notes',
    length: 'Length (Full or Desired)',
    bust: 'Bust',
    
    // Additional Measurements
    torsoLength: 'Torso Length',
    waistPosition: 'Waist Position (High/Mid/Low)',
    bodyHeight: 'Body Height',
    bustRoundEase: 'Bust Round with Ease',
    maternityEase: 'Maternity Ease Allowance',
    jumpsuitCrotchLength: 'Jumpsuit Crotch Length',
    waist: 'Waist',
    hip: 'Hip',
    shoulder: 'Shoulder',
    armhole: 'Armhole',
    sleeveLength: 'Sleeve Length',
    sleeveRound: 'Sleeve Round',
    neckDepthFront: 'Neck Depth (Front)',
    neckDepthBack: 'Neck Depth (Back)',
    neckWidth: 'Neck Width',
    sideSlitLength: 'Side Slit Length',
    bottomOpeningRound: 'Bottom Opening Round',
    thighRound: 'Thigh Round',
    kneeRound: 'Knee Round',
    calfRound: 'Calf Round',
    ankleRound: 'Ankle Round',
    inseamLength: 'Inseam Length',
    outseamLength: 'Outseam Length',
    salwarBeltHeight: 'Salwar Belt Height (Kamar Patti)',
    ghera: 'Ghera of Salwar / Hem Width',
    churidarLength: 'Churidar Length',
    ankleFit: 'Ankle Fit',
    underbust: 'Underbust',
    shoulderWidth: 'Shoulder Width',
    blouseLength: 'Blouse Length',
    frontNeck: 'Front Neck',
    backNeck: 'Back Neck',
    waistToKnee: 'Waist to Knee',
    waistToAnkle: 'Waist to Ankle',
    bodyHeight: 'Body Height',
    bustRoundEase: 'Bust Round with Ease',
    maternityEase: 'Maternity Ease Allowance',
    jumpsuitCrotchLength: 'Jumpsuit Crotch Length',
    acrossFront: 'Across Front',
    acrossBack: 'Across Back',
    bustPointDistance: 'Bust Point to Bust Point (Apex Distance)',
    underbustLength: 'Underbust Length',
    backOpeningWidth: 'Back Opening Width',
    doriLength: 'Dori Length (if needed)',
    lehengaLength: 'Lehenga Length',
    bottomGhera: 'Bottom Ghera',
    zipPreference: 'Zip preference',
    canCanRequirement: 'Can-can requirement',
    fullLength: 'Full Length',
    neckDepth: 'Neck Depth',
    
    // Common
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    loading: 'Loading...',
    permissionRequired: 'Permission Required',
    cameraRollPermission: 'Please grant permission to access your photo library',
    failedToPickImage: 'Failed to pick image',
    success: 'Success',
    retry: 'Retry',
    close: 'Close',
    confirm: 'Confirm',
    yes: 'Yes',
    no: 'No',
    search: 'Search',
    order: 'Order',
    currentStatus: 'Current Status',
    balance: 'Balance',
    username: 'Username',
    password: 'Password',
    signIn: 'Sign In',
    welcomeBack: 'Welcome Back',
    signInToYourTailorShop: 'Sign in to your tailor shop',
    
    // Navigation Titles
    customers: 'Customers',
    addCustomer: 'Add Customer',
    addOrder: 'Add Order',
    orders: 'Orders',
    orderDetails: 'Order Details',
    measurements: 'Measurements',
    customerOrders: 'Customer Orders',
    logout: 'Logout',
    
    // Placeholders
    searchByOrderNumber: 'Search by order number...',
    selectDeliveryDate: 'Select delivery date',
    enterTotalAmount: 'Enter total amount',
    enterAdvanceAmount: 'Enter advance amount',
    enterOrderNotes: 'Enter order notes',
    enterMeasurementValue: 'Enter measurement value',
    
    // Enhanced HomeScreen
    recentActivities: 'Recent Activities',
    recentOrders: 'Recent Orders',
    recentCustomers: 'Recent Customers',
    viewAndManageCustomers: 'View and manage customers',
    addNewCustomer: 'Add new customer',
    viewAndManageOrders: 'View and manage orders',
    createNewOrder: 'Create new order',
    areYouSureToLogout: 'Are you sure you want to logout?',
    
    // Order List Filter
    showing: 'Showing',
    clearFilter: 'Clear Filter',
    noFilteredOrders: 'No {status} orders found',
    
    // Language
    language: 'Language',
    selectLanguage: 'Select Language',
    english: 'English',
    gujarati: 'Gujarati',
  },
  gu: {
    // Navigation
    home: 'હોમ',
    customers: 'ગ્રાહકો',
    orders: 'ઓર્ડર',
    
    // Home Screen
    welcome: 'સ્વાગત',
    businessOverview: 'વ્યવસાય અવલોકન',
    quickActions: 'ઝડપી ક્રિયાઓ',
    totalCustomers: 'કુલ ગ્રાહકો',
    totalOrders: 'કુલ ઓર્ડર',
    pendingOrders: 'બાકી ઓર્ડર',
    completedOrders: 'પૂર્ણ થયેલ ઓર્ડર',
    tailorShop: 'ટેલર શોપ',
    recentOrders: 'તાજેતરના ઓર્ડર',
    noOrders: 'કોઈ ઓર્ડર મળ્યા નહીં',
    addCustomer: 'ગ્રાહક ઉમેરો',
    addOrder: 'ઓર્ડર ઉમેરો',
    viewAll: 'બધું જુઓ',
    quickActions: 'ઝડપી ક્રિયાઓ',
    
    // Customer Screen
    customersList: 'ગ્રાહકોની સૂચિ',
    searchNameContact: 'નામ અથવા સંપર્ક શોધો...',
    addNewCustomer: 'નવા ગ્રાહક ઉમેરો',
    customerName: 'ગ્રાહકનું નામ',
    contactNumber: 'સંપર્ક નંબર',
    address: 'સરનામું',
    saveCustomer: 'ગ્રાહક સાચવો',
    updateCustomer: 'ગ્રાહક અપડેટ કરો',
    customerNumber: 'ગ્રાહક નંબર',
    viewOrders: 'ઓર્ડર જુઓ',
    edit: 'સંપાદિત કરો',
    delete: 'કાઢી નાખો',
    noCustomersFound: 'કોઈ ગ્રાહકો મળ્યા નહીં',
    noOrdersFound: 'કોઈ ઓર્ડર મળ્યા નહીં',
    totalOrders: 'કુલ ઓર્ડર',
    
    // Order Screen
    ordersList: 'ઓર્ડરની સૂચિ',
    orderNumber: 'ઓર્ડર નંબર',
    customer: 'ગ્રાહક',
    orderDate: 'ઓર્ડર તારીખ',
    deliveryDate: 'ડિલિવરી તારીખ',
    status: 'સ્થિતિ',
    amount: 'રકમ',
    pending: 'બાકી',
    in_progress: 'પ્રગતિમાં',
    ready: 'તૈયાર',
    delivered: 'પહોંચાડેલ',
    cancelled: 'રદ કરેલ',
    createOrder: 'ઓર્ડર બનાવો',
    updateOrder: 'ઓર્ડર અપડેટ કરો',
    orderDetails: 'ઓર્ડર વિગતો',
    paymentInformation: 'ચુકવણી માહિતી',
    updateStatus: 'સ્થિતિ અપડેટ કરો',
    deleteOrder: 'ઓર્ડર કાઢી નાખો',
    viewOrders: 'ઓર્ડર જુઓ',
    
    // Add/Edit Order
    createNewOrder: 'નવો ઓર્ડર બનાવો',
    editOrder: 'ઓર્ડર સંપાદિત કરો',
    customerRequired: 'ગ્રાહક *',
    garmentTypes: 'કપડાના પ્રકાર',
    measurements: 'માપ',
    designImage: 'ડિઝાઇન ઇમેજ',
    totalAmount: 'કુલ રકમ *',
    advanceAmount: 'અડવાન્સ રકમ',
    notes: 'નોંધ',
    balanceAmount: 'બાકી રકમ',
    
    // Measurements
    measurementType: 'માપનો પ્રકાર',
    value: 'કિંમત',
    unit: 'એકમ',
    saveMeasurements: 'માપ સાચવો',
    
    // Garment Types
    selectGarmentTypes: 'કપડાના પ્રકાર પસંદ કરો *',
    kurtiKameezTop: 'કુર્તી / કમીઝ / ટોપ',
    salwarPantChuridar: 'સલવાર / પેન્ટ / ચુરિદાર',
    blouseSareeBlouse: 'બ્લાઉસ (સાડી બ્લાઉસ)',
    lehengaSkirt: 'લેહેંગા / સ્કર્ટ',
    gownAnarkali: 'ગાઉન / અનારકલી',
    dressWesternWear: 'ડ્રેસ / વેસ્ટર્ન વેર',
    other: 'અન્ય',
    pleaseSelectAtLeastOneGarmentType: 'કૃપા કરીને ઓછામાં ઓછો એક કપડાનો પ્રકાર પસંદ કરો',
    
    // Add Order Screen
    noCustomerSelected: 'કોઈ ગ્રાહક પસંદ કરેલ નથી',
    selectCustomer: 'ગ્રાહક પસંદ કરો',
    customerId: 'ગ્રાહક ID',
    hide: 'છુપાવો',
    show: 'બતાવો',
    remove: 'દૂર કરો',
    tapToUploadDesign: '📷 ડિઝાઇન અપલોડ કરવા ટેપ કરો',
    updatingOrder: 'ઓર્ડર અપડેટ કરી રહ્યા છીએ...',
    creatingOrder: 'ઓર્ડર બનાવી રહ્યા છીએ...',
    addDesignImage: 'ડિઝાઇન ઇમેજ ઉમેરો',
    totalAmountRequired: 'કૃપા કરીને કુલ રકમ દાખલ કરો',
    garmentTypesRequired: 'કૃપા કરીને ઓછામાં ઓછો એક કપડાનો પ્રકાર પસંદ કરો',
    orderCreatedSuccessfully: 'ઓર્ડર સફળતાપૂર્વક બનાવ્યો',
    orderUpdatedSuccessfully: 'ઓર્ડર સફળતાપૂર્વક અપડેટ થયો',
    failedToSaveOrder: 'ઓર્ડર સાચવવામાં નિષ્ફળ. કૃપા કરીને બધા ફીલ્ડ્સ તપાસો અને ફરી પ્રયાસ કરો.',
    failedToCreateOrder: 'ઓર્ડર બનાવવામાં નિષ્ફળ. કૃપા કરીને ફરી પ્રયાસ કરો.',
    failedToUpdateOrder: 'ઓર્ડર અપડેટ કરવામાં નિષ્ફળ. કૃપા કરીને ફરી પ્રયાસ કરો.',
    failedToLoadDesignImage: 'ડિઝાઇન ઇમેજ લોડ કરવામાં નિષ્ફળ. કૃપા કરીને ફરી પ્રયાસ કરો.',
    
    // Alert Messages
    failedToLoadOrders: 'ઓર્ડર લોડ કરવામાં અસમર્થ. કૃપા કરીને તમારું જોડાણ તપાસો અને ફરી પ્રયાસ કરો.',
    failedToSearchOrders: 'શોધ પૂર્ણ થઈ પરંતુ કોઈ પરિણામો મળ્યા નથી. કૃપા કરીને અલગ શોધ શબ્દોનો ઉપયોગ કરો.',
    deleteOrder: 'ઓર્ડર કાઢી નાખો',
    deleteOrderConfirmation: 'શું તમે ખરેખર ઓર્ડર #{orderNumber} કાઢી નાખવા માંગો છો? આ ક્રિયા પાછી પાળી શકાતી નથી.',
    orderDeletedSuccessfully: 'ઓર્ડર સફળતાપૂર્વક કાઢી નાખવામાં આવ્યો',
    failedToDeleteOrder: 'ઓર્ડર કાઢી નાખવામાં અસમર્થ. કૃપા કરીને ફરી પ્રયાસ કરો.',
    orderStatusUpdatedSuccessfully: 'ઓર્ડરની સ્થિતિ સફળતાપૂર્વક અપડેટ કરાઈ',
    failedToUpdateOrderStatus: 'ઓર્ડરની સ્થિતિ અપડેટ કરવામાં અસમર્થ. કૃપા કરીને ફરી પ્રયાસ કરો.',
    
    // Error Messages
    error: 'ભૂલ',
    loginFailed: 'લોગિન નિષ્ફળ',
    anErrorOccurredDuringLogin: 'સાઇન ઇન કરવામાં અસમર્થ. કૃપા કરીને તમારા લોગિન વિગતો તપાસો અને ફરી પ્રયાસ કરો.',
    pleaseEnterBothUsernameAndPassword: 'આગળ વધવા માટે બંને વપરાશકર્તા નામ અને પાસવર્ડ જરૂરી છે.',
    customerNameRequired: 'ગ્રાહકનું નામ જરૂરી છે. કૃપા કરીને માન્ય નામ દાખલ કરો.',
    customerUpdatedSuccessfully: 'ગ્રાહકની માહિતી સફળતાપૂર્વક અપડેટ થઈ',
    customerAddedSuccessfully: 'નવા ગ્રાહક સફળતાપૂર્વક ઉમેરાયા',
    failedToSaveCustomer: 'ગ્રાહકની માહિતી સાચવવામાં અસમર્થ. કૃપા કરીને બધા ફીલ્ડ્સ તપાસો અને ફરી પ્રયાસ કરો.',
    failedToLoadCustomers: 'ગ્રાહક યાદી લોડ કરવામાં અસમર્થ. કૃપા કરીને રિફ્રેશ કરો અને ફરી પ્રયાસ કરો.',
    failedToSearchCustomers: 'તમારી શોધ શરતો સાથે બંધબેસતા કોઈ ગ્રાહકો મળ્યા નથી.',
    deleteCustomer: 'ગ્રાહક કાઢી નાખો',
    deleteCustomerConfirmation: 'શું તમે ખરેખર {customerName} કાઢી નાખવા માંગો છો? સંબંધિત ઓર્ડરો રહેશે પરંતુ ગ્રાહકની વિગતો કાયમ માટે દૂર થઈ જશે.',
    customerDeletedSuccessfully: 'ગ્રાહક સફળતાપૂર્વક કાઢી નાખવામાં આવ્યો',
    failedToDeleteCustomer: 'ગ્રાહકને કાઢી નાખવામાં અસમર્થ. કૃપા કરીને ફરી પ્રયાસ કરો.',
    measurementsSavedSuccessfully: 'માપ સફળતાપૂર્વક સાચવાયા',
    failedToSaveMeasurements: 'માપ સાચવવામાં અસમર્થ. કૃપા કરીને બધા મૂલ્યો ચકાસો અને ફરી પ્રયાસ કરો.',
    connectionError: 'જોડાણ ભૂલ',
    cannotConnectToBackendServer: 'સર્વર સાથે જોડાવામાં અસમર્થ. કૃપા કરીને સુનિશ્ચિત કરો કે તમારું ઇન્ટરનેટ જોડાણ સક્રિય છે અને બેકએન્ડ સર્વર ચાલી રહ્યું છે.',
    retry: 'ફરી પ્રયાસ કરો',
    ok: 'ઠીક છે',
    cancel: 'રદ કરો',
    select: 'પસંદ કરો',
    saving: 'સાચવી રહ્યા છીએ...',
    failedToLoadOrderDetails: 'ઓર્ડરની વિગતો લોડ કરવામાં અસમર્થ. કૃપા કરીને રિફ્રેશ કરો અને ફરી પ્રયાસ કરો.',
    confirmDeleteOrder: 'શું તમે ખરેખર આ ઓર્ડર કાઢી નાખવા માંગો છો? આ ક્રિયા પાછી પાળી શકાતી નથી.',
    
    // Placeholders
    enterYourUsername: 'તમારું વપરાશકર્તા નામ દાખલ કરો',
    enterYourPassword: 'તમારો પાસવર્ડ દાખલ કરો',
    enterCustomerName: 'ગ્રાહકનું નામ દાખલ કરો',
    enterContactNumber: 'સંપર્ક નંબર દાખલ કરો',
    enterCustomerAddress: 'ગ્રાહકનું સરનામું દાખલ કરો',
    searchNameOrContact: 'નામ અથવા સંપર્ક શોધો...',
    
    // Image Picker
    selectImageSource: 'છબી સ્ત્રોત પસંદ કરો',
    chooseImageSource: 'તમે છબી કેવી રીતે ઉમેરવા માંગો છો તે પસંદ કરો',
    camera: 'કેમેરા',
    gallery: 'ગેલરી',
    permissionRequired: 'પરવાનગી જરૂરી',
    cameraPermission: 'ફોટો લેવા માટે કેમેરા પરવાનગી જરૂરી છે. કૃપા કરીને તમારા ઉપકરણની સેટિંગ્સમાં કેમેરા ઍક્સેસ સક્ષમ કરો.',
    cameraRollPermission: 'છબીઓ પસંદ કરવા માટે ફોટો લાઇબ્રેરી પરવાનગી જરૂરી છે. કૃપા કરીને તમારા ઉપકરણની સેટિંગ્સમાં ફોટો ઍક્સેસ સક્ષમ કરો.',
    failedToPickImage: 'છબી પસંદ કરવામાં અસમર્થ. કૃપા કરીને ફરી પ્રયાસ કરો.',
    designImage: 'ડિઝાઇન છબી',
    tapToUploadDesign: '📷 ડિઝાઇન છબી અપલોડ કરવા ટેપ કરો',
    viewFullScreen: 'પૂર્ણ સ્ક્રીન જુઓ',
    customer: 'ગ્રાહક',
    customerNumber: 'ગ્રાહક #:',
    phone: 'ફોન',
    address: 'સરનામું',
    nA: 'ઉપલબ્ધ નથી',
    order: 'ઓર્ડર',
    orders: 'ઓર્ડર',
    loadingOrders: 'ઓર્ડર લોડ થઈ રહ્યા છે...',
    failedToLoadOrdersError: 'ઓર્ડર લોડ કરવામાં નિષ્ફળ',
    
    // DatePicker
    january: 'જાન્યુઆરી',
    february: 'ફેબ્રુઆરી',
    march: 'માર્ચ',
    april: 'એપ્રિલ',
    may: 'મે',
    june: 'જૂન',
    july: 'જુલાઈ',
    august: 'ઑગસ્ટ',
    september: 'સપ્ટેમ્બર',
    october: 'ઑક્ટોબર',
    november: 'નવેમ્બર',
    december: 'ડિસેમ્બર',
    
    // API Error Messages
    loginFailedError: 'લોગિન નિષ્ફળ',
    failedToFetchCustomers: 'ગ્રાહકોને લાવવામાં નિષ્ફળ',
    failedToFetchCustomerDetails: 'ગ્રાહકની વિગતો લાવવામાં નિષ્ફળ',
    failedToAddCustomer: 'ગ્રાહકને ઉમેરવામાં નિષ્ફળ',
    failedToUpdateCustomer: 'ગ્રાહકને અપડેટ કરવામાં નિષ્ફળ',
    failedToDeleteCustomer: 'ગ્રાહકને કાઢી નાખવામાં નિષ્ફળ',
    failedToFetchOrders: 'ઓર્ડરને લાવવામાં નિષ્ફળ',
    failedToFetchOrderDetails: 'ઓર્ડરની વિગતો લાવવામાં નિષ્ફળ',
    failedToAddOrder: 'ઓર્ડરને ઉમેરવામાં નિષ્ફળ',
    failedToUpdateOrder: 'ઓર્ડરને અપડેટ કરવામાં નિષ્ફળ',
    failedToDeleteOrder: 'ઓર્ડરને કાઢી નાખવામાં નિષ્ફળ',
    
    // Order Detail Screen
    failedToLoadOrderDetails: 'ઓર્ડરની વિગતો લોડ કરવામાં નિષ્ફળ',
    confirmDeleteOrder: 'શું તમે ખરેખર આ ઓર્ડર કાઢી નાખવા માંગો છો?',
    failedToDeleteOrder: 'ઓર્ડર કાઢી નાખવામાં નિષ્ફળ',
    
    // Measurement Screen
    general: 'સામાન્ય',
    customNotesPlaceholder: 'કોઈપણ કસ્ટમ માપ નોંધ અથવા વિશિષ્ટ આવશ્યકતાઓ ઉમેરો...',
    additionalMeasurements: 'વધારાના માપ',
    customNotes: 'કસ્ટમ નોંધ',
    length: 'લંબાઈ (પૂરી અથવા ઇચ્છિત)',
    bust: 'છાતી',
    
    // Additional Measurements
    torsoLength: 'ટોર્સો લંબાઈ',
    waistPosition: 'કમરની સ્થિતિ (ઉચ્ચ/મધ્ય/નીચું)',
    bodyHeight: 'શરીરની ઊંચાઈ',
    bustRoundEase: 'આરામ સાથે છાતીનો ફેરો',
    maternityEase: 'મેટરનિટી સરળંગતની પરવાનગી',
    jumpsuitCrotchLength: 'જમ્પસૂટ ક્રોચ લંબાઈ',
    waist: 'કમર',
    hip: 'નિતંબ',
    shoulder: 'ખભું',
    armhole: 'આર્મહોલ',
    sleeveLength: 'સ્લીવ લંબાઈ',
    sleeveRound: 'સ્લીવ ફરતે',
    neckDepthFront: 'ગળાની ઊંડાઈ (સામે)',
    neckDepthBack: 'ગળાની ઊંડાઈ (પાછળ)',
    neckWidth: 'ગળાની પહોળાઈ',
    sideSlitLength: 'બાજુની સ્લિટ લંબાઈ',
    bottomOpeningRound: 'નીચેનું ઓપનિંગ ફરતે',
    thighRound: 'જાંઘ ફરતે',
    kneeRound: 'ઘૂંટણ ફરતે',
    calfRound: 'પિંડલી ફરતે',
    ankleRound: 'ગોળા ફરતે',
    inseamLength: 'ઇનસીમ લંબાઈ',
    outseamLength: 'આઉટસીમ લંબાઈ',
    salwarBeltHeight: 'સલવાર બેલ્ટ ઊંચાઈ (કમર પટ્ટી)',
    ghera: 'સલવારનું ઘેરા / હેમ પહોળાઈ',
    churidarLength: 'ચુરિદાર લંબાઈ',
    ankleFit: 'ગોળા ફિટ',
    underbust: 'છાતી નીચે',
    shoulderWidth: 'ખભાની પહોળાઈ',
    blouseLength: 'બ્લાઉસ લંબાઈ',
    frontNeck: 'સામેનું ગળું',
    backNeck: 'પાછળનું ગળું',
    waistToKnee: 'કમરથી ઘૂંટણ સુધી',
    waistToAnkle: 'કમરથી ગોળા સુધી',
    bodyHeight: 'શરીરની ઊંચાઈ',
    bustRoundEase: 'છાતી ફરતે ઈઝ સાથે',
    maternityEase: 'મેટરનિટી ઈઝ એલાઉન્સ',
    jumpsuitCrotchLength: 'જમ્પસ્યુટ ક્રોચ લંબાઈ',
    acrossFront: 'સામે આડી',
    acrossBack: 'પાછળ આડી',
    bustPointDistance: 'છાતીના બિંદુથી છાતીના બિંદુ સુધીનું અંતર (એપેક્સ અંતર)',
    underbustLength: 'છાતી નીચેની લંબાઈ',
    backOpeningWidth: 'પાછળની ઓપનિંગ પહોળાઈ',
    doriLength: 'ડોરીની લંબાઈ (જો જરૂરી હોય)',
    lehengaLength: 'લેહેંગા લંબાઈ',
    bottomGhera: 'નીચેનું ઘેરા',
    zipPreference: 'ઝિપ પસંદગી',
    canCanRequirement: 'કેન-કેન આવશ્યકતા',
    fullLength: 'સંપૂર્ણ લંબાઈ',
    neckDepth: 'ગળાની ઊંડાઈ',
    
    // Order Statuses
    pending: 'બાકી',
    in_progress: 'પ્રગતિમાં',
    ready: 'તૈયાર',
    delivered: 'પહોંચાડેલ',
    cancelled: 'રદ કરેલ',
    additionalMeasurements: 'વધારાના માપ',
    customNotes: 'કસ્ટમ નોંધ',
    
    // Common
    save: 'સાચવો',
    cancel: 'રદ કરો',
    delete: 'કાઢી નાખો',
    edit: 'સંપાદિત કરો',
    loading: 'લોડ થઈ રહ્યું છે...',
    permissionRequired: 'પરવાનગી જરૂરી',
    cameraRollPermission: 'કૃપા કરીને તમારા ફોટો લાઇબ્રેરીની પહોંચ માટે પરવાનગી આપો',
    failedToPickImage: 'ચિત્ર પસંદ કરવામાં નિષ્ફળ',
    error: 'ભૂલ',
    success: 'સફળતા',
    retry: 'ફરી પ્રયાસ કરો',
    close: 'બંધ કરો',
    confirm: 'પુષ્ટિ કરો',
    yes: 'હા',
    no: 'ના',
    search: 'શોધો',
    order: 'ઓર્ડર',
    currentStatus: 'વર્તમાન સ્થિતિ',
    balance: 'બાકી',
    username: 'વપરાશકર્તા નામ',
    password: 'પાસવર્ડ',
    signIn: 'સાઇન ઇન',
    welcomeBack: 'પાછા આવનું સ્વાગત',
    signInToYourTailorShop: 'તમારી ટેલર દુકાનમાં સાઇન ઇન કરો',
    
    // Navigation Titles
    customers: 'ગ્રાહકો',
    addCustomer: 'ગ્રાહક ઉમેરો',
    addOrder: 'ઓર્ડર ઉમેરો',
    orders: 'ઓર્ડર',
    orderDetails: 'ઓર્ડર વિગતો',
    measurements: 'માપ',
    customerOrders: 'ગ્રાહક ઓર્ડર',
    logout: 'લોગઆઉટ',
    
    // Placeholders
    searchByOrderNumber: 'ઓર્ડર નંબર દ્વારા શોધો...',
    selectDeliveryDate: 'ડિલિવરી તારીખ પસંદ કરો',
    enterTotalAmount: 'કુલ રકમ દાખલ કરો',
    enterAdvanceAmount: 'અડવાન્સ રકમ દાખલ કરો',
    enterOrderNotes: 'ઓર્ડર નોંધ દાખલ કરો',
    enterMeasurementValue: 'માપની કિંમત દાખલ કરો',
    
    // Enhanced HomeScreen
    recentActivities: 'તાજેરી પ્રવૃત્તિઓ',
    recentOrders: 'તાજેરા ઓર્ડર',
    recentCustomers: 'તાજેરા ગ્રાહકો',
    viewAndManageCustomers: 'ગ્રાહકો જોઓ અને સંચાલિત કરો',
    addNewCustomer: 'નવો ગ્રાહક ઉમેરો',
    viewAndManageOrders: 'ઓર્ડર જોઓ અને સંચાલિત કરો',
    createNewOrder: 'નવો ઓર્ડર બનાવો',
    areYouSureToLogout: 'શું તમે ખરેખર લોગઆઉટ કરવા માંગો છો?',
    
    // Order List Filter
    showing: 'દર્શાવી રહ્યા છીએ',
    clearFilter: 'ફિલ્ટર સાફ કરો',
    noFilteredOrders: 'કોઈ {status} ઓર્ડર મળ્યા નથી',
    
    // Language
    language: 'ભાષા',
    selectLanguage: 'ભાષા પસંદ કરો',
    english: 'અંગ્રેજી',
    gujarati: 'ગુજરાતી',
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en'); // Default to English

  const changeLanguage = (lang) => {
    setLanguage(lang);
  };

  const t = (key) => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export default LanguageContext;
